version: '3.4'

services:
  postgresql: 
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=MainDb
    restart: always
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      - postgresql
    ports:
      - "5000:80"
        
  
volumes:
  postgres_data:
  pgadmin_data:
    